services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./nginx/html:/var/www/html
    depends_on:
      - apache
    networks:
      - mynetwork

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./apache:/var/www/html
    expose:
      - "80"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
